// LOCALHOST
### GET all users

GET http://localhost:3000/users

//get contact
###
GET http://localhost:3000/users/66efa9b098dc3a7778cffed0


### create contact

POST http://localhost:3000/users HTTP/1.1
Content-Type: application/json

{
    "email": "John00@gmail.com",
    "username": "vampi080800",
    "name":"jonns",
    "ipaddress":"2.6.4.5.5."
}
### Put contac
PUT http://localhost:3000/users/66ef7ae3af9c96b46ec2c7f1 HTTP/1.1
Content-Type: application/json

{
    "email": "John00@gmail.com",
    "username": "vampi080800",
    "name":"jonns",
    "ipaddress":"2.6.4.5.5."
}
### delete
DELETE http://localhost:3000/users/66f824a67ece04b23cc7148a  HTTP/1.1

